HH-1 stream tasks
Ziyakaev/Stream_task pull request #1
Opened 2020-11-28 14:44 UTC by Ziyakaev

solve tasks and comment create in PR

2020-11-28 14:50 UTC, Ziyakaev commented on src/tasks/Task1.java
> +    }
Если я прав то сложность 2*O(N) . Чтобы быстро отсортировать нам нужно соответствие айди на клиента.

2020-11-28 14:55 UTC, Ziyakaev commented on src/tasks/Task2.java
>    }
Самое простое создать одну большую коллекцию и ее отсортировать.  2 способ это отсортировать каждые элементы по отдельности и потом сортировать 2 отсортированные коллекции, мне показалось это одно и то же, поэтому первый вариант.

2020-11-28 14:55 UTC, Ziyakaev commented on src/tasks/Task3.java
Хотел сначала написать свой компаратор, а оно вон как работает.

2020-11-28 14:58 UTC, Ziyakaev commented on src/tasks/Task4.java
> +	}
идее не нравится лямбда, наверное можно лаконичнее как то сделать, но думаю и так красиво.

2020-11-28 15:02 UTC, Ziyakaev commented on src/tasks/Task6.java
>    }
самая интересная и сложная задача.  Нужны соответствия айди на клиента, и айди на регион. Пройтись personAreaIds : для каждого клиента по всем регионам создать еще стрим который превратим в множество строк

2020-11-28 15:04 UTC, Ziyakaev commented on src/tasks/Task7.java
>    }
аналогично как в предыдущей задаче

2020-11-28 15:06 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
не понравилось что принимаем лист и отдаем лист, можно было заменить на collection но это зависит от условии задачи. пропускаем один элемент и преобразуем в список строк

2020-11-28 15:08 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
прошлая реализация возможно круче так как в getNames передаем уже список уникальных клиентов

2020-11-28 15:09 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
очень удобно

2020-11-28 15:09 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
если ключи совпадают то оставляем старый ключ

2020-11-28 15:11 UTC, Ziyakaev commented on src/tasks/Task8.java
создал тесты для проверки работоспособности. не стал делить проверки на разные методы.

2020-11-28 15:13 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
мне казалось плохой практикой передавать в  параметрах стрим.

2020-11-30 08:29 UTC, genroelgvozo requested changes

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task1.java
> +      // O(N)
Это почему это O(n)? это же просто создание мапы с выделением массива. Вот сколько там ОС тратить на выделение массива вообще неочевидно, далеко не факт что там линейная зависимость

Но это ладно, превращение в мапу таки способом - не очень. Намного лаконичнее стримы с коллект ту мап

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task1.java
> +      persons.forEach(p -> idByPerson.put(p.getId(), p));
Даже в лямбде лучше именовать нормально переменные (person)
но правда я выше написал что там все проще делается, чем так

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task1.java
> +      if (persons == null || persons.isEmpty()) {
ну проверка на null такое себе,  у тебя сервис возвращает список персон, null в таких случаях антипаттерн, если он не нашел, логично что вернет пустой список
А вот нужна ли проверка на пустой список? Чтобы только быстрее выйти из функции? Код ниже разве сломается если список будет пустой? Такие лишние проверки нужны, только если действительно ниже код не сработает, и надо рассмотреть крайний случай (у вас дальше будет хибернейт, и там будет такая нужда иногда). Здесь же лишний код всегда лишний, это не оптимизация, а только нагрузка на чтение кода))

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task1.java
> +              .map(id -> idByPerson.get(id))
ну а тут вопросов нет, идея правильная, только с мапой поправить.
Еще можно idByPerson::get писать (идея небось подсказывает что так лучше)

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task1.java
> +    }
ну да, но только в сложностях нет константных множителей)) все это O(n) (весь код работает линейно от кол-ва элементов, а уж сколько операций над каждым совершается - 2,3 или 10 - неважно, и кстати там не 2 если разбирать подробно)

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task2.java
>    }
да, но только вот вопрос как создать большую коллекцию. Ты создаешь третью, потом кладешь в нее вторую, посмотри на Stream.concat или на flatMap в стримах

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task3.java
да, оно так работает) вопросов нет

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task3.java
> +		Instant time = Instant.now();
Вообще на будущее, не надо править файл там где ты его не правишь) всегда говори идеи брать стили те, которые уже находятся в файле (у нас в хх отступы 2 и 4, а не 4 и 8). Получается у тебя ПР с кучей дифа, из которого я должен вычленять именно твои правки, а не твоего чекстайла

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task4.java
> +	}
ну раз не нравится, то почему не поправил как советует?)
Ссылка на метод всегда лучше Task4::convert

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task4.java
> +	}
Про нейминг даже в лямбдах выше писал

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task5.java
> +            .map(v -> convert(v, personAreaIds.get(v.getId())))
аналогично нейминг. А так все ок

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task6.java
>    }
все ок, но можно от первой мапы избавиться
Бежать просто по персонам, и у них внутри flatMap обращаться к personAreaIds и там уже формировать имя + регоин (вторая мапа твоя нужна)
Тем самым меньше мап + не нужен entrySet c его getValue getKey которые возвращают хз что (мне как читателю кода очень трудно вникнуть)

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task7.java
>    }
1) Дистинкт не нужен, у тебя же сет
2) map лучше выносить за flatMap, чтобы не думать к какому стриму этот мап применяется. Т.е. флатмап заканчивай как можно раньше

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task8.java
> +	}
эмм, ну принимаем лист, и пропускаем ПЕРВУЮ персону, т.е. логично что лист
Отдаем лист потому что наверное логично отдать строки в том же порядке что и персоны изначально)

А что еще не понравилось?) чем принципиально скип лучше чем ремув?

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task8.java
> +	}
нет конечно, надо так как ты написал
в getNames передаем изначальный persons же, стрим берется уже от результата а не от persons
тут идея что во-первых distinct лишний, а дальше и стрим значит лишний, потому что можно через конструктор)

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task8.java
> +	}
Согласен)

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task8.java
> +	}
Вот тут ты решил в лямбде именовать так именовать)) но в мерж функции обычно допускается запись типо (a,b) -> a (из двух выбираем первый, все понятно)
 А тут какой-то кей, че блин) И кстати может я на лекции неправильно сказал, но она принимает значения а не ключ (ключи то одинаковые, а значения может и разные, и надо среди них выбрать)

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task8.java
> +		return persons1.stream().anyMatch(v -> persons2.contains((v)));
Гуд, но вопрос, за сколько выполняется код? От чего зависит?) Как сделать чтобы быстро было всегда?
Ну и persons2::contains

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task8.java
> +	}
А почему так казалось?) И чем изначальный код плох был?

2020-11-30 08:29 UTC, genroelgvozo commented on src/tasks/Task8.java
> -    boolean reviewerDrunk = false;
ведь можно было просто поставить тру... 😄

2020-11-30 09:26 UTC, Ziyakaev commented on src/tasks/Task2.java
>    }
Поправил через concat.

2020-11-30 09:27 UTC, Ziyakaev commented on src/tasks/Task4.java
> +	}
поправил

2020-11-30 09:35 UTC, Ziyakaev commented on src/tasks/Task6.java
>    }
поправил

2020-11-30 09:37 UTC, Ziyakaev commented on src/tasks/Task7.java
>    }
поправил

2020-11-30 10:18 UTC, Ziyakaev commented on src/tasks/Task1.java
> +      // O(N)
31 строка указывала на строку ниже - заполнение мапы.
исправил на стрим

2020-11-30 10:19 UTC, Ziyakaev commented on src/tasks/Task1.java
> +              .map(id -> idByPerson.get(id))
подсказывает, когда пишешь idByPerson если нет, то не подсказывает. поправил

2020-11-30 10:24 UTC, Ziyakaev commented on src/tasks/Task5.java
> +            .map(v -> convert(v, personAreaIds.get(v.getId())))
поправил

2020-11-30 15:26 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
вдруг мы отдали стрим который уже использовали.  менее читабельный старый код и дополнительно завели переменную. В новом если бы не применяли фильтр то реализация count могла подсчитывать данных из исходных данных стрима

2020-11-30 15:38 UTC, Ziyakaev commented on src/tasks/Task8.java
> +		return persons1.stream().anyMatch(v -> persons2.contains((v)));
сложность O^2(N) в худшем случае, зависит от реализации коллекции. вторую коллекцию преобразовать в set .

2020-11-30 15:39 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
исправил

2020-11-30 15:45 UTC, Ziyakaev commented on src/tasks/Task8.java
> +	}
чтобы удалить первый элемент обязательно нужна проверка которая была на 30 строке и мы затрачиваем время на удаление если реализация у коллекции была arrayList

2020-11-30 15:47 UTC, Ziyakaev commented on src/tasks/Task3.java
> +		Instant time = Instant.now();
буду знать..

2020-11-30 15:51 UTC, Ziyakaev commented on src/tasks/Task1.java
> +      if (persons == null || persons.isEmpty()) {
проверка на пустой список избыточна да.

2020-12-02 12:12 UTC, genroelgvozo commented on src/tasks/Task8.java
> +	}
Ну время ок, но на самом деле принципиальное различие - исходный код модифицировал входящую коллекцию (она по ссылке же передается). И это не рекомендуется, пользователь функции не ожидает что параметры изменятся). Это относится не только к коллекциям (но иногда бывает направленное обогащение, типо updateDtoWithPersons(Dto dto, List<Integer> personIds - она своим названием говорит что положит в дто персон, т.е. поменяет дто). Но лучше такого избегать

2020-12-02 12:15 UTC, genroelgvozo commented on src/tasks/Task8.java
> +	}
ок, все верно. Еще был шанс догадаться до параллельности, стрим может быть параллельным, и тогда исходный код просто выдавал неверный результат (при большом кол-ве элементов)

2020-12-02 12:27 UTC, genroelgvozo approved these changes

2020-12-02 12:27 UTC, genroelgvozo commented on src/tasks/Task2.java
>    }
конкат норм)
через флат мап - Stream.of(persons1, persons2).flatMap(Collection::stream)

2020-12-02 12:27 UTC, genroelgvozo commented on src/tasks/Task6.java
>    }
так ну сейчас все ок, но нейминг..)
править уже не надо, но запомни, что в лямбдах тоже стоит писать норм (и почему v выбрал для person?))

2020-12-02 12:27 UTC, genroelgvozo commented on src/tasks/Task7.java
>    }
про map не стал править? имел в виду
.flatMap(company -> company.getVacancies().stream).map(Vacancy::getTitle) чтобы мап уже к внешнему применялся
Можно даже
.map(Company::getVacancies)
.flatMap(Collection::getStream)
.map(Vacancy::getTitle)

2020-12-02 12:27 UTC, genroelgvozo commented on src/tasks/Task8.java
> +		return persons1.stream().anyMatch(persons2::contains);
про сет ответил но править не стал) ну короче можно было new HashSet<>(persons2)::contains

2020-12-02 12:42 UTC, Ziyakaev commented on src/tasks/Task6.java
>    }
v - value)

2020-12-09 08:58 UTC, merged